spring.application.name=liga-futbol-api
server.port=8088

# MongoDB Atlas (cluster "equipos"). Se puede sobreescribir con la variable de entorno MONGODB_URI
spring.data.mongodb.uri=mongodb+srv://keynerbueno12_db_user:1615@pcprofesor.yl4zcd2.mongodb.net/mundial?appName=pcprofesor

# Mostrar el mensaje de error en las respuestas (404, 409, etc.)
server.error.include-message=always

# Carga datos de ejemplo la primera vez (solo si la coleccion "club" esta vacia)
app.seed.enabled=true

